refactor: define EDITOR variable

diff --git a/installer/functions/environment b/installer/functions/environment
--- a/installer/functions/environment
+++ b/installer/functions/environment
@@ -13,3 +13,12 @@ safety() {
 load_rvm() {
   source ~/.rvm/scripts/rvm
 }
+
+define_editor() {
+  if [[ "${EDITOR:-unset}" == "unset" ]]; then
+    say "What program do you want to use for editing the configuration file?"
+    read -s choice
+    command -v $choice >/dev/null 2>&1 || fatal "The editor could not be found."
+    EDITOR=$choice
+  fi
+}
