offer editing db configuration file

diff --git a/installer/functions/system-user-install b/installer/functions/system-user-install
--- a/installer/functions/system-user-install
+++ b/installer/functions/system-user-install
@@ -94,6 +94,22 @@ setup_db() {
     cp database.yaml.example database.yaml
   fi
 
+  skip_decision "Do you want to edit the configuration file now?" && (\
+    # ask if $EDITOR is undefined
+    if [[ "${EDITOR:-unset}" == "unset" ]]; then
+      say "What program do you want to use for editing the database configuration file?"
+      read -s choice
+      command -v $choice >/dev/null 2>&1 || fatal "The editor could not be found."
+      EDITOR=$choice
+    else
+      say "Opening database configuration file for editing tasks."
+      say "Please press a key to continue."
+      read -n1
+    fi
+
+    $EDITOR database.yaml
+  )
+
   safety off
     cd rb
     rvm use --create 1.9.3@libertree-db
